export const imagePath = {
  TODO_ACTIVE: require('./images/todo-active.png'),
  TODO_INACTIVE: require('./images/todo-inactive.png'),
  HISTORY_ACTIVE: require('./images/history-active.png'),
  HISTORY_INACTIVE: require('./images/history-inactive.png'),
  CREATE_TODO: require('./images/create-todo.png'),
  CHECK: require('./images/check.png'),
  UNCHECK: require('./images/un-check.png'),
  HIGH_PRIORITY: require('./images/high.png'),
  NORMAL_PRIORITY: require('./images/normal.png'),
  LOW_PRIORITY: require('./images/low.png'),
  EDIT: require('./images/edit.png'),
  DELETE: require('./images/delete.png'),
  BACK: require('./images/back.png'),
};
